steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kanban-346815/kanban-board-api', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kanban-346815/kanban-board-api']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'kanban-board-api',
        '--image',
        'gcr.io/kanban-346815/kanban-board-api',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--port',
        '3000',
      ]
images:
  - gcr.io/kanban-346815/kanban-board-api
